const NAMES: Record<string, string> = {
  eng: 'English',
  en: 'English',
  por: 'Portuguese',
  pt: 'Portuguese',
  spa: 'Spanish',
  es: 'Spanish',
  fre: 'French',
  fra: 'French',
  fr: 'French',
  ger: 'German',
  deu: 'German',
  de: 'German',
  ita: 'Italian',
  it: 'Italian',
  dut: 'Dutch',
  nld: 'Dutch',
  nl: 'Dutch',
  rus: 'Russian',
  ru: 'Russian',
  jpn: 'Japanese',
  ja: 'Japanese',
  chi: 'Chinese',
  zho: 'Chinese',
  zh: 'Chinese',
  kor: 'Korean',
  ko: 'Korean',
  ara: 'Arabic',
  ar: 'Arabic',
  heb: 'Hebrew',
  he: 'Hebrew',
  swe: 'Swedish',
  sv: 'Swedish',
  nor: 'Norwegian',
  no: 'Norwegian',
  dan: 'Danish',
  da: 'Danish',
  fin: 'Finnish',
  fi: 'Finnish',
  pol: 'Polish',
  pl: 'Polish',
  cze: 'Czech',
  ces: 'Czech',
  cs: 'Czech',
  gre: 'Greek',
  ell: 'Greek',
  el: 'Greek',
  tur: 'Turkish',
  tr: 'Turkish',
  hin: 'Hindi',
  hi: 'Hindi',
  lat: 'Latin',
  la: 'Latin',
  ukr: 'Ukrainian',
  uk: 'Ukrainian',
  hun: 'Hungarian',
  hu: 'Hungarian',
  rom: 'Romanian',
  ron: 'Romanian',
  ro: 'Romanian',
  cat: 'Catalan',
  ca: 'Catalan',
  gle: 'Irish',
  ga: 'Irish',
  isl: 'Icelandic',
  is: 'Icelandic',
}

export function languageName(code: string | null | undefined): string | null {
  if (!code) return null
  const key = code.trim().toLowerCase()
  if (!key) return null
  return NAMES[key] ?? code.trim()
}
